
interface InvoiceData {
  invoiceNumber: string;
  date: string;
  userName: string;
  userEmail: string;
  planName: string;
  amount: number;
  currency: string;
  paymentMethod: string;
}

/**
 * Generates a professional PDF Invoice buffer
 */
export async function generateInvoicePDF(data: InvoiceData): Promise<Buffer> {
  const { default: jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");

  const doc = new jsPDF();
  const primaryColor: [number, number, number] = [109, 40, 217]; // #6d28d9

  // --- Header ---
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, 210, 40, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("DRIPLARE AI", 15, 20);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Official Payment Receipt", 15, 30);
  doc.text(`Invoice #: ${data.invoiceNumber}`, 140, 20);
  doc.text(`Date: ${data.date}`, 140, 28);

  // --- Billing Details ---
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Bill To:", 15, 55);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(data.userName, 15, 62);
  doc.text(data.userEmail, 15, 68);

  // --- Item Table ---
  autoTable(doc, {
    startY: 80,
    head: [["Description", "Qty", "Price", "Total"]],
    body: [
      [
        `REMOVED AI - ${data.planName.toUpperCase()} Plan Subscription`,
        "1",
        `${data.amount} ${data.currency.toUpperCase()}`,
        `${data.amount} ${data.currency.toUpperCase()}`
      ]
    ],
    theme: "striped",
    headStyles: { fillColor: primaryColor },
    margin: { left: 15, right: 15 }
  });

  // --- Summary ---
  const finalY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(`Total Amount Paid:`, 115, finalY);
  doc.text(`${data.amount} ${data.currency.toUpperCase()}`, 195, finalY, { align: "right" });
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(`Payment Gateway: ${data.paymentMethod.toUpperCase()}`, 15, finalY);

  // --- Signatures Section ---
  const signatureY = 250;

  // Left: Customer Signature
  doc.setLineWidth(0.5);
  doc.line(15, signatureY, 75, signatureY); // Line
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Signature of the customer", 15, signatureY + 5);

  // Right: CEO Signature
  const rightAlignX = 195;
  
  try {
    const fs = await import("fs");
    const path = await import("path");
    const imagePath = path.join(process.cwd(), "public", "CEO-Sign.jpg");
    
    if (fs.existsSync(imagePath)) {
      const imageData = fs.readFileSync(imagePath);
      const base64Image = imageData.toString("base64");
      // Add CEO Signature image (adjust size as needed)
      doc.addImage(base64Image, "JPEG", 145, signatureY - 25, 45, 20);
    }
  } catch (err) {
    console.error("Signature image loading failed:", err);
  }

  doc.line(135, signatureY, 195, signatureY); // Line
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Sajid Sorker", rightAlignX, signatureY + 5, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Founder & CEO, REMOVED AI", rightAlignX, signatureY + 10, { align: "right" });

  // --- Footer ---
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text("Generated by REMOVED AI Billing System", 105, 285, { align: "center" });

  return Buffer.from(doc.output("arraybuffer"));
}
