import "server-only";

// ─────────────────────────────────────────────────────────────
// lib/pdf/core.ts
// Shared PDF utilities — header, footer, signature.
// All PDF templates should use these helpers for consistent branding.
// ─────────────────────────────────────────────────────────────

/** Brand colours */
export const PDF_BRAND = {
  primary: [109, 40, 217] as [number, number, number],   // #6d28d9 violet
  dark: [30, 20, 50] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  gray: [120, 120, 130] as [number, number, number],
  lightGray: [245, 244, 248] as [number, number, number],
  success: [16, 185, 129] as [number, number, number],   // emerald
  warning: [245, 158, 11] as [number, number, number],   // amber
  danger: [239, 68, 68] as [number, number, number],     // red
};

/** Page constants */
export const PAGE = { W: 210, H: 297, MARGIN: 15 };

/** DRIPLARE brand name */
export const BRAND_NAME = "DRIPLARE AI";
export const BRAND_TAGLINE = "driplare.com";
export const BRAND_EMAIL = "support@driplare.com";
export const CEO_NAME = "Sajid Sorker";
export const CEO_TITLE = "Founder & CEO, Driplare AI";

// ─────────────────────────────────────────────────────────────
// Dynamic jsPDF import helper (works server-side)
// ─────────────────────────────────────────────────────────────

export async function createDoc() {
  const { default: jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  return { doc, autoTable };
}

export function drawGradient(
  doc: any,
  x: number,
  y: number,
  w: number,
  h: number,
  colorStart: [number, number, number],
  colorEnd: [number, number, number]
) {
  const steps = 60;
  const stepHeight = h / steps;
  for (let i = 0; i < steps; i++) {
    const ratio = i / (steps - 1);
    const r = Math.round(colorStart[0] + ratio * (colorEnd[0] - colorStart[0]));
    const g = Math.round(colorStart[1] + ratio * (colorEnd[1] - colorStart[1]));
    const b = Math.round(colorStart[2] + ratio * (colorEnd[2] - colorStart[2]));
    doc.setFillColor(r, g, b);
    // Draw with slight overlap to prevent thin white lines
    doc.rect(x, y + i * stepHeight, w, stepHeight + 0.1, "F");
  }
}

// ─────────────────────────────────────────────────────────────
// drawHeader — gradient band at the top with logo text
// ─────────────────────────────────────────────────────────────

export async function drawHeader(doc: any, subtitle: string) {
  const { W, MARGIN } = PAGE;
  const colorStart = PDF_BRAND.primary;
  const colorEnd: [number, number, number] = [79, 70, 229]; // Indigo

  // Premium gradient header
  drawGradient(doc, 0, 0, W, 36, colorStart, colorEnd);

  // Subtle accent band
  doc.setFillColor(140, 80, 240);
  doc.rect(0, 32, W, 4, "F");

  // Brand logo or text fallback
  let logoLoaded = false;
  try {
    const fs = await import("fs");
    const path = await import("path");
    const logoPath = path.join(process.cwd(), "public", "header-logo-white.png");
    if (fs.existsSync(logoPath)) {
      const logoData = fs.readFileSync(logoPath).toString("base64");
      doc.addImage(logoData, "PNG", MARGIN, 7, 36, 12);
      logoLoaded = true;
    }
  } catch {
    // Fallback silently
  }

  if (!logoLoaded) {
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(BRAND_NAME, MARGIN, 15);
  }

  // Subtitle (e.g. "Payment Invoice" / "Plan Change Notification")
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(255, 255, 255);
  doc.text(subtitle, MARGIN, 26);

  // Right-aligned website
  doc.setFontSize(9);
  doc.setTextColor(255, 255, 255);
  doc.text(BRAND_TAGLINE, W - MARGIN, 26, { align: "right" });
}

// ─────────────────────────────────────────────────────────────
// drawFooter — bottom note
// ─────────────────────────────────────────────────────────────

export function drawFooter(doc: any, note = "") {
  const { W, H, MARGIN } = PAGE;

  // Thin separator line
  doc.setDrawColor(220, 218, 230);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, H - 18, W - MARGIN, H - 18);

  doc.setFontSize(7.5);
  doc.setTextColor(...PDF_BRAND.gray);
  doc.text(
    `Generated by ${BRAND_NAME} Billing System  •  ${new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}`,
    W / 2,
    H - 12,
    { align: "center" }
  );
  if (note) {
    doc.text(note, W / 2, H - 7, { align: "center" });
  }
}

// ─────────────────────────────────────────────────────────────
// drawSignatureBlock — CEO signature image + lines
// ─────────────────────────────────────────────────────────────

export async function drawSignatureBlock(doc: any, yPos: number) {
  const { W, MARGIN } = PAGE;
  const rightX = W - MARGIN;

  // Left: Customer signature placeholder
  doc.setDrawColor(...PDF_BRAND.gray);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, yPos, MARGIN + 60, yPos);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...PDF_BRAND.gray);
  doc.text("Signature of Customer", MARGIN, yPos + 5);

  // Right: CEO signature image
  try {
    const fs = await import("fs");
    const path = await import("path");
    const imgPath = path.join(process.cwd(), "public", "CEO-Sign.jpg");
    if (fs.existsSync(imgPath)) {
      const imgData = fs.readFileSync(imgPath).toString("base64");
      doc.addImage(imgData, "JPEG", rightX - 55, yPos - 22, 55, 18);
    }
  } catch {
    // Signature image not found — skip silently
  }

  doc.line(rightX - 60, yPos, rightX, yPos);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PDF_BRAND.dark);
  doc.text(CEO_NAME, rightX, yPos + 5, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...PDF_BRAND.gray);
  doc.text(CEO_TITLE, rightX, yPos + 10, { align: "right" });
}

// ─────────────────────────────────────────────────────────────
// drawSectionLabel — small uppercase section heading
// ─────────────────────────────────────────────────────────────

export function drawSectionLabel(doc: any, text: string, y: number) {
  doc.setFontSize(7.5);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PDF_BRAND.gray);
  doc.text(text.toUpperCase(), PAGE.MARGIN, y);
}

// ─────────────────────────────────────────────────────────────
// drawInfoBox — coloured info panel
// ─────────────────────────────────────────────────────────────

export function drawInfoBox(
  doc: any,
  x: number,
  y: number,
  w: number,
  h: number,
  color: [number, number, number],
  opacity = 0.08
) {
  doc.setFillColor(color[0], color[1], color[2]);
  if (typeof doc.GState === "function") {
    doc.setGState(doc.GState({ opacity }));
  }
  doc.roundedRect(x, y, w, h, 2, 2, "F");
  if (typeof doc.GState === "function") {
    doc.setGState(doc.GState({ opacity: 1 }));
  }
}
