import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from "@/components/theme-provider";
import { I18nProvider } from "@/components/i18n-provider";
import { RegionProvider } from "@/components/region-provider";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import { ConfirmModal } from "@/components/modals/confirm-modal";
import { cookies } from "next/headers";
import { Suspense } from "react";
import { ReferralTracker } from "@/components/ReferralTracker";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const regionCookie = cookieStore.get("driplare_region")?.value;
  const initialRegion = (regionCookie === "global" ? "global" : "bd") as "bd" | "global";

  return (
    <ClerkProvider>
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <RegionProvider initialRegion={initialRegion}>
            <I18nProvider>
              {children}
              <Toaster position="top-right" richColors />
              <ConfirmModal />
              <Suspense fallback={null}>
                <ReferralTracker />
              </Suspense>
            </I18nProvider>
            </RegionProvider>
          </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
